### PR TITLE
Fixes #1118 - Getting started guide fails?

### LINKED ISSUE #1118: Getting started guide fails?
I'm running through the getting started guide, found in this repo's README.md and off your vimeo page.  I'm going along and everything is peachy until:

```
❯❯❯ snapctl task create -t mock-file.yaml
Using task manifest to create task
Error creating task:
Plugin not found: type(publisher) name(mock-file) version(-1)
```

I open up the yaml and check out that its looking for a publisher named "mock-file" and not "file", run `snapctl plugin unload publisher:file:1`  followed by 
`snapctl plugin load plugins/snap-plugin-publisher-mock-file` .  I then run the task create again:

```
❯❯❯ snapctl task create -t mock-file.yaml
Using task manifest to create task
Task created
ID: cd9697b4-dcc4-4e3b-a8c2-1d4955bae9be
Name: Task-cd9697b4-dcc4-4e3b-a8c2-1d4955bae9be
```

seems better, but now: 

```
❯❯❯ snapctl task list
ID 					 NAME 						 STATE 		 HIT 	 MISS 	 FAIL 	 CREATED 		 LAST FAILURE
cd9697b4-dcc4-4e3b-a8c2-1d4955bae9be 	 Task-cd9697b4-dcc4-4e3b-a8c2-1d4955bae9be 	 Disabled 	 10 	 0 	 10 	 12:01PM 8-01-2016 	 Publish call error: EOF
```

and in the console output of snapd: 

```
DEBU[2016-08-01T12:01:14-04:00] level=debug msg="publishing started"          _module=plugin-exec io=stderr plugin=snap-plugin-publisher-mock-file
DEBU[2016-08-01T12:01:14-04:00] level=error msg="error decoding" content=[13 255 147 2 1 2 255 148 0 1 255 136 0 0 255 155 255 135 3 1 1 10 77 101 116 114 105 99 84 121 112 101 1 255 136 0 1 9 1 10 78 97 109 101 115 112 97 99 101 95 1 255 140 0 1 19 76 97 115 116 65 100 118 101 114 116 105 115 101 100 84 105 109 101 95 1 255 142 0 1 8 86 101 114 115 105 111 110 95 1 4 0 1 7 67 111 110 102 105 103 95 1 255 144 0 1 5 68 97 116 97 95 1 16 0 1 5 84 97 103 115 95 1 255 146 0 1 5 85 110 105 116 95 1 12 0 1 12 68 101 115 99 114 105 112 116 105 111 110 95 1 12 0 1 10 84 105 109 101 115 116 97 109 112 95 1 255 142 0 0 0 38 255 139 2 1 1 23 91 93 99 111 114 101 46 78 97 109 101 115 112 97 99 101 69 108 101 109 101 110 116 1 255 140 0 1 255 138 0 0 65 255 137 3 1 1 16 78 97 109 101 115 112 97 99 101 69 108 101 109 101 110 116 1 255 138 0 1 3 1 5 86 97 108 117 101 1 12 0 1 11 68 101 115 99 114 105 112 116 105 111 110 1 12 0 1 4 78 97 109 101 1 12 0 0 0 16 255 141 5 1 1 4 84 105 109 101 1 255 142 0 0 0 10 255 143 5 1 2 255 150 0 0 0 33 255 145 4 1 1 17 109 97 112 91 115 116 114 105 110 103 93 115 116 114 105 110 103 1 255 146 0 1 12 1 12 0 0] error=EOF   _module=plugin-exec io=stderr plugin=snap-plugin-publisher-mock-file
ERRO[2016-08-01T12:01:14-04:00] error with publisher job                      _module=scheduler-job block=run content-type=snap.gob error=Publish call error: EOF job-type=publisher plugin-config=map[file:{Value:/tmp/snap_published_mock_file.log} debug:{Value:true}] plugin-name=mock-file plugin-version=-1
WARN[2016-08-01T12:01:14-04:00] Publish job failed 
```

Until the fail limit of 10 consecutive fails is reached and it aborts completely.

I've retried the whole process using the plain "file" plugin (and rewriting the yaml), I've also changed the target file to a file/folder with 777 permissions, selinux and firewalls off.  And I get the same thing every time.  Being as new to this framework as I am (following the getting started guide), any ideas as to what could be wrong?

### PR DESCRIPTION
**Pull request by jcooklin**
Fixes #1118 

Sets the current time as the advertised time in the returned metric when using grpc.

Summary of changes:
- Ensures that the advertised time of the metric is set when calling GetMetricTypes (from grpc client)
- Checks that the advertised time is set when converting a grpc/common/metric to a core.Metric

Testing done:
- Manual
- Unit

@intelsdi-x/snap-maintainers

### CODE REVIEW

File: grpc/common/common.go [hunk 1]
```diff
@@ -127,12 +127,20 @@ func (m *metric) Unit() string                  { return m.unit }
 
 // Convert common.Metric to core.Metric
 func ToCoreMetric(mt *Metric) core.Metric {
+	var lastAdvertisedTime time.Time
+	// if the lastAdvertisedTime is not set we handle.  -62135596800 represents the
+	// number of seconds from 0001-1970 and is the default value for time.Unix.
+	if mt.LastAdvertisedTime.Sec == int64(-62135596800) {
```
Comment (lmroz) [inline grpc/common/common.go]: This is quite unexpected to have time replaced by Now() during conversion.

**Comment by lmroz** [comment]
I bet on that this issue is caused by fractional timezone set when unmarshalling data from grpc (by calling `time.Unix()`), not getting empty data from there. So during conversion to `time.Time` it should be moved to UTC time zone. Perhaps this is not going to fix the issue because I doubt that behavior of `Now()` will be different than `Unix()`.

File: grpc/common/common.go (hunk 1 above)
Comment (nanliu) [inline grpc/common/common.go]: This is due to timezone switch to LMT (not sure the exact cut off dates). Maybe another option is to only log in UTC?

```
$ go_time
t: 1900-01-01 00:00:00 +0000 UTC t in Local: 1899-12-31 16:07:02 -0752 LMT
t2: 2000-01-01 00:00:00 +0000 UTC t2 in Local: 1999-12-31 16:00:00 -0800 PST
```

Comment (lmroz) [inline grpc/common/common.go]: Wow, good catch @nanliu . I haven't been aware of that some places in the world (maybe Poland too, gotta check) had in the past different and fractional "time zone" ...and PCs actually take this into account :100:

**Comment by danielscottt** [comment]
LGTM
