### PR TITLE
Fixes #1582: Snap framework panics when using autoload feature and REST API is down

### LINKED ISSUE #1582: Snap framework panics when using `auto_discover_path` feature and REST API is down.
**Environment**:
- **OS**: Ubuntu 16.04
- **Kernel**: 4.4.0-71-generic 

**Problem:**
The situation occurs and is reproducible when using `auto_discover_path` feature and starting `snapteld` with incorrect REST API configuration (i.e. on port 8181 when it is taken by another application). 

Snapteld reports panic:
```
user@hostname:/var/log/snap# /usr/bin/snapteld -l 1 -t 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x57e67c]

goroutine 1 [running]:
panic(0xad9b80, 0xc420010090)
	/home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/intelsdi-x/snap/mgmt/rest.(*Server).run(0xc42014c2c0, 0xc4203fb090, 0x5)
	/home/travis/gopath/src/github.com/intelsdi-x/snap/mgmt/rest/server.go:266 +0x52c
github.com/intelsdi-x/snap/mgmt/rest.(*Server).Start(0xc42014c2c0, 0xc4203072e0, 0x1)
	/home/travis/gopath/src/github.com/intelsdi-x/snap/mgmt/rest/server.go:213 +0x9f
main.startModule(0xf1ca20, 0xc42014c2c0, 0x1, 0x1)
	/home/travis/gopath/src/github.com/intelsdi-x/snap/snapteld.go:978 +0x49
main.action(0xc42024dcc0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/intelsdi-x/snap/snapteld.go:380 +0xd8d
github.com/intelsdi-x/snap/vendor/github.com/urfave/cli.HandleAction(0xab2200, 0xc1aca0, 0xc42024dcc0, 0xc420189d40, 0x0)
	/home/travis/gopath/src/github.com/intelsdi-x/snap/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/intelsdi-x/snap/vendor/github.com/urfave/cli.(*App).Run(0xc42008b6c0, 0xc42000a0a0, 0x5, 0x5, 0x0, 0x0)
	/home/travis/gopath/src/github.com/intelsdi-x/snap/vendor/github.com/urfave/cli/app.go:259 +0x74f
main.main()
	/home/travis/gopath/src/github.com/intelsdi-x/snap/snapteld.go:220 +0x705
```
instead of the explaining the actual reason:
```
FATA[2017-04-03T12:09:59Z] listen tcp :8181: listen: address already in use 
```
The lack of message makes it impossible for the user to guess what was the actual cause of the panic.
The message about the already taken port reveals itself only after disabling autoload feature.

### PR DESCRIPTION
**Pull request by rashmigottipati**
Fixes #1582 

Summary of changes:
- Log the bind error as a fatal message thereby avoiding the panic to occur. This log message is consistent with/without using the autoload feature.

Steps to reproduce:

1) `snapteld -l 1 -t 0 --control-listen-port 8084`

2) In another terminal, run snapteld without auto-discovery: 
`snapteld -l 1 -t 0`
You should receive the following error:
FATA[2017-04-18T14:49:14-07:00] listen tcp :8181: bind: address already in use
This is expected behavior. 

Let's try to do the same with autodiscovery option:
`snapteld -a "/opt/snap/plugins" -t 0 -l 1`
This causes a panic:
INFO[2017-04-18T14:23:13-07:00] Starting REST API on :8181                    _module=_mgmt-rest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x17937c]

As I user, I expect to receive an error with appropriate message that port 8181 is already in use, without causing panic.

Testing done:
- Manual testing

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by candysmurf** [comment]
LGTM

File: mgmt/rest/server.go [hunk 1]
```diff
@@ -252,15 +252,15 @@ func (s *Server) run(addrString string) {
...
-			s.err <- err
+			log.Fatal(err)
 		}
 		s.serverListener = ln
 		s.wg.Add(1)
 		go s.serveTLS(ln)
 	} else {
 		ln, err := net.Listen("tcp", addrString)
 		if err != nil {
-			s.err <- err
```
Comment (IzabellaRaulin) [inline mgmt/rest/server.go]: There is mechanism of monitoring errors [see here: monitorErrors](https://github.com/intelsdi-x/snap/blob/master/snapteld.go#L379) using `err channel`:
```
func monitorErrors(ch <-chan error) {
	// Block on the error channel. Will return exit status 1 for an error or just return if the channel closes.
	err, ok := <-ch
	if !ok {
		return
	}
	log.Fatal(err)
}
```
So just add "return" after lines 255 and 263 are enough to avoid panic, **but** after such change the logs are confusing - I mean log "REST started" appears as a first one ([see here](https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/server.go#L214)) even it is not true.
```
INFO[2017-04-19T15:42:31+02:00] Starting REST API on :8181                    _module=_mgmt-rest
INFO[2017-04-19T15:42:31+02:00] REST started                                  _block=start _module=_mgmt-rest
INFO[2017-04-19T15:42:31+02:00] module started                                _module=snapteld block=main snap-module=REST
INFO[2017-04-19T15:42:31+02:00] setting plugin trust level to: disabled
INFO[2017-04-19T15:42:31+02:00] snapteld started
FATA[2017-04-19T15:42:31+02:00] listen tcp :8181: bind: address already in use
```
I just want to share my observations about this with you. Basically, I am ok with logging Fatal as soon as possible. I have just concerns if there are other similar issues and about what next with that existing `monitorErrors` - is it still need and should be kept or there is a plan to remove it.
