### PR TITLE
Fix #657: Pass deadline for a task from task manifest or from command line for a workflow manifest

### LINKED ISSUE #657: Task deadline is not propagated from task manifest or from snapctl cli for a workflow manifest
Referenced from #655 

Found the issue why adding deadline to the task manifest is not working. We have deadline support on the server side of the REST api, but the client and the command line tool currently do not support the deadline option from the task manifest as seen here https://github.com/intelsdi-x/snap/blob/master/cmd/snapctl/task.go#L86-L91 and here https://github.com/intelsdi-x/snap/blob/master/mgmt/rest/client/task.go#L50-L58.

### PR DESCRIPTION
**Pull request by geauxvirtual**
This issue was found while troubleshooting #655. Task deadline was implemented in the REST api and in the TaskCreationRequest, but was not implemented in the REST client code or snapctl.

This PR adds support for specifying the deadline in a task manifest or on the command line for a workflow manifest via the --deadline flag.

### CODE REVIEW

File: core/task.go [hunk 1]
```diff
@@ -98,6 +98,14 @@ func TaskDeadlineDuration(v time.Duration) TaskOption {
 	return func(t Task) TaskOption {
 		previous := t.DeadlineDuration()
 		t.SetDeadlineDuration(v)
+		log.WithFields(log.Fields{
+			"_module":                   "core",
+			"_block":                    "TaskDeadlineDuration",
+			"task-id":                   t.ID(),
+			"task-name":                 t.GetName(),
+			"consecutive failure limit": t.DeadlineDuration(),
```
Comment (thomastaylor312) [inline core/task.go]: Should the field name for this be called `consecutive failure limit`?

Comment (geauxvirtual) [inline core/task.go]: Good catch. Bad copy and paste job last night.

**Comment by danielscottt** [comment]
LGTM
