### PR TITLE
Fixes pool eligibility #910

### LINKED ISSUE #910: Pool eligibility incorrectly calculated for concurrency count > 1
Function ```pool.Eligible()``` does not work properly for cases where ```p.concurrencyCount > 1``` 

Main condition:

```go
should := p.SubscriptionCount() / p.concurrencyCount
if should > p.Count() && should <= p.max {
    return true
}
return false
```
Let's assume maximum pool size to 3 and only one instance of available plugin in the pool 
```go
p.max = 3
p.Count() = 1
``` 
then

|p.SubscriptionCount()|p.concurrencyCount|should|Eligible|Expected|
| :------: |:------:| :------:| :------: | :------: |
| 1 | 2 | 0 |False | False |
| 2 | 2 | 1 |False | False |
| 3 | 2 | 1 |False | True |
| 4 | 2 | 2 |False | True |
| 5 | 2 | 2 |False | True |
| 6 | 2 | 3 |True | True |

Suggested solution:

```go
should := p.SubscriptionCount() > p.concurrencyCount * p.Count()
oversized := p.SubscriptionCount() > p.concurrencyCount * p.max
if should  && !oversized {
    return true
}
return false
```

### PR DESCRIPTION
**Pull request by marcin-krolik**
Fixes #910 

Summary of changes:
- changed condition for eligibility

Testing done:
- unit tests

@intelsdi-x/snap-maintainers

Pool eligibility was not calculated properly for concurrency count > 1

### CODE REVIEW

File: control/strategy/pool.go [hunk 1]
```diff
@@ -270,8 +270,9 @@ func (p *pool) Eligible() bool {
 		return false
 	}
 
-	should := p.SubscriptionCount() / p.concurrencyCount
-	if should > p.Count() && should <= p.max {
+	should := p.SubscriptionCount() > p.concurrencyCount*p.Count()
+	// Check if pool is eligible and number of plugins is less than maximum allowed
+	if should && p.Count() < p.max {
```
Comment (IRCody) [inline control/strategy/pool.go]: I'm wondering if we should change the code at 269 to be:
```go
if p.Count() >= p.max {
        return false
}
``` 
This would capture the case where plugin count went over the max and ensure that when we get to the next statement p.Count() < p.max. Then we could modify this if-statement to check only:
```go
if p.SubscriptionCount() > p.ConcurrencyCount*p.Count() {
       return true
}
```

Comment (marcin-krolik) [inline control/strategy/pool.go]: I was thinking about the same. Code looked to verbose, but I decided to leave it that way. But you are right.

**Comment by IRCody** [comment]
LGTM

**Comment by candysmurf** [comment]
LGTM too. But it's better to check with @jcooklin & @geauxvirtual as I had doubt on the calculation before. I'm not sure any reason it did like that.
