### PR TITLE
fix #534: panic on metric tree lookup with trailing slash

### LINKED ISSUE #534: curl http://127.0.0.1:8181/v1/metrics/ panics (only with trailing /)
/tasks/ and /plugins/ redirect to /tasks and /plugins, but `curl http://127.0.0.1:8181/v1/metrics/` panics with:
```
PANIC: runtime error: index out of range
goroutine 87 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0xf09d80, 0xc820145e40, 0xc820f86780)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/recovery.go:34 +0xe9
github.com/intelsdi-x/pulse/mgmt/rest.parseNamespace(0xc82011846f, 0x1, 0x0, 0x0, 0x0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/intelsdi-x/pulse/mgmt/rest/server.go:272 +0x113
github.com/intelsdi-x/pulse/mgmt/rest.(*Server).getMetricsFromTree(0xc820124a80, 0xf09d80, 0xc820145e40, 0xc8200b21c0, 0xc820118580, 0x1, 0x1)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/intelsdi-x/pulse/mgmt/rest/metric.go:44 +0x8a
github.com/intelsdi-x/pulse/mgmt/rest.(*Server).(github.com/intelsdi-x/pulse/mgmt/rest.getMetricsFromTree)-fm(0xf09d80, 0xc820145e40, 0xc8200b21c0, 0xc820118580, 0x1, 0x1)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/intelsdi-x/pulse/mgmt/rest/server.go:210 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc820113bc0, 0xf09d80, 0xc820145e40, 0xc8200b21c0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/julienschmidt/httprouter/router.go:299 +0x193
github.com/codegangsta/negroni.Wrap.func1(0xf09d80, 0xc820145e40, 0xc8200b21c0, 0xc820118560)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/negroni.go:41 +0x50
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc820f86820, 0xf09d80, 0xc820145e40, 0xc8200b21c0, 0xc820118560)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/negroni.go:24 +0x44
github.com/codegangsta/negroni.middleware.ServeHTTP(0xf09a48, 0xc820f86820, 0xc820f868a0, 0xf09d80, 0xc820145e40, 0xc8200b21c0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0xf09d80, 0xc820145e40, 0xc8200b21c0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/codegangsta/negroni.(*Recovery).ServeHTTP(0xc820f86780, 0xf09d80, 0xc820145e40, 0xc8200b21c0, 0xc820118520)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/recovery.go:45 +0x75
github.com/codegangsta/negroni.middleware.ServeHTTP(0xf09a20, 0xc820f86780, 0xc820f86860, 0xf09d80, 0xc820145e40, 0xc8200b21c0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0xf09d80, 0xc820145e40, 0xc8200b21c0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/intelsdi-x/pulse/mgmt/rest.(*Logger).ServeHTTP(0xc820114120, 0xf09d80, 0xc820145e40, 0xc8200b21c0, 0xc8201184c0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/intelsdi-x/pulse/mgmt/rest/log_handler.go:46 +0x387
github.com/codegangsta/negroni.middleware.ServeHTTP(0xf099f8, 0xc820114120, 0xc820f86840, 0xf09d80, 0xc820145e40, 0xc8200b21c0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc820113b30, 0xf09ce8, 0xc8200984d0, 0xc8200b21c0)
	/Users/tjerniga/.gvm/pkgsets/system/global/src/github.com/codegangsta/negroni/negroni.go:73 +0x122
net/http.serverHandler.ServeHTTP(0xc820124b40, 0xf09ce8, 0xc8200984d0, 0xc8200b21c0)
	/Users/tjerniga/.gvm/gos/go1.5/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820099130)
	/Users/tjerniga/.gvm/gos/go1.5/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/Users/tjerniga/.gvm/gos/go1.5/src/net/http/server.go:1910 +0x3f6
```

In server.go it makes ns len 0 and then tries accessing ns[0]
```go
func parseNamespace(ns string) []string {
	if strings.Index(ns, "/") == 0 {
		ns = ns[1:]
	}
	ns[len(ns)-1] == '/' {
		ns = ns[:len(ns)-1]
	}
	return strings.Split(ns, "/")
}
```

Should be 
```go
if len(ns) > 0 && ns[len(ns)-1] == '/' 
``` 
instead

Not sure what about : instead of * makes the GET redirect (though it would break the rest of namespace)
e.g. 
```
curl http://127.0.0.1:8181/v1/plugins/
<a href="/v1/plugins">Moved Permanently</a>.
```
Going to http://127.0.0.1:8181/v1/metrics/ seems fine and redirects to /metrics, but http://localhost:8181/v1/metrics/ mimics the curl with a panic.

### PR DESCRIPTION
**Pull request by danielscottt**

### CODE REVIEW

File: mgmt/rest/metric.go [hunk 1]
```diff
@@ -41,6 +41,15 @@ func (s *Server) getMetrics(w http.ResponseWriter, r *http.Request, _ httprouter
...
+	// we land here if the request contains a trailing slash, because it matches the tree
+	// lookup URL: /v1/metrics/*namespace.  If the length of the namespace param is 1, we
+	// redirect the request to getMetrics.  This results in GET /v1/metrics and
+	// GET /v1/metrics/ behaving the same way.
+	if len(params.ByName("namespace")) <= 1 {
+		s.getMetrics(w, r, params)
+		return
+	}
+
 	ns := parseNamespace(params.ByName("namespace"))
```
Comment (candysmurf) [inline mgmt/rest/metric.go]: probably add a var for params.ByName("namespace") instead of calling it twice. Good work!

**Comment by candysmurf** [comment]
LGTM :thumbsup:
