### PR TITLE
Fix for issue #1167, added handling of errors which are returned by scaner

### LINKED ISSUE #1167: Errors during capturing of stderr from plugins
It seems that there is an issue with capturing logs from plugin which are sent to stderr. The issue was observed using the cpu plugin. 

I've prepared the special versions of cpu plugin to observe what if plugin sends logs frequently:
- cpu plugin with frequent short log, the version is available [here](https://github.com/katarzyna-z/snap-plugin-collector-cpu/commit/a79c0a040d6308a9276a54d2e6f8cd27581f8b95), 
- cpu plugin with long log, the version is is available [here](https://github.com/katarzyna-z/snap-plugin-collector-cpu/commit/9738a2b2145067d19cb5e3c776ec9d233428b204).

I've tested this two special versions of cpu plugin with two version of snap:
- snap with capturing of logs from plugins, it is this [commit](https://github.com/intelsdi-x/snap/commit/5d91b04fa8b7d398fea04f5cbbe970f21cf32bd9),
- snap without capturing of logs from plugins, it is this [commit]( https://github.com/intelsdi-x/snap/commit/84aa75e8074ecbf633b43d07a96a12aa43f6861a).

I've observed that errors appear only in snap with capturing of logs from plugins. It seems that there is a problem in capturing stderr from plugins when log line is long. In the snap version without capturing of logs from plugins there was a special case for errors returned by the scanner, please see [this](https://github.com/intelsdi-x/snap/commit/5d91b04fa8b7d398fea04f5cbbe970f21cf32bd9#diff-9263d577284097ec1bec3e3fce13eb32L328) .

It could be fixed on plugin side (by adding a newline at the end of the log) but it will be good to have a protection also on snap side.

### PR DESCRIPTION
**Pull request by katarzyna-z**
Fixes #1167 

Hanging of plugins during capturing of stderr and stdout were observed when log line had a significant length. It was caused by errors occured during scanning of stderr or stdout. Errors returned by Scan()  were not handled by snapd. 

To fix the issue used the method which was used before adding of log capturing from plugin [commit]( https://github.com/intelsdi-x/snap/commit/5d91b04fa8b7d398fea04f5cbbe970f21cf32bd9) so now goto procedure is in use to deal with long line of logs.

Summary of changes:
- Added handling of errors returned by Scan method in the part of code which is used to capture stdout and stderr from plugins,
- Modified mock plugin to test log lines with significant length.

Testing done:
- Verified tests pass for small, medium, and legacy.
- Manual tests with mock plugin.

@intelsdi-x/snap-maintainers

### CODE REVIEW

File: control/plugin/execution.go [hunk 1]
```diff
@@ -131,6 +132,25 @@ func (e *ExecutablePlugin) Run(timeout time.Duration) (Response, error) {
 				}).Debug(stdOutScanner.Text())
 			}
 		}
+
+		if err := stdOutScanner.Err(); err != nil {
+			if err == bufio.ErrTooLong {
+				reader := bufio.NewReader(e.stdout)
+				log, _, _ := reader.ReadLine()
```
Comment (IRCody) [inline control/plugin/execution.go]: Why `Readline` vs `ReadString('\n')`?

File: control/plugin/execution.go [hunk 2]
```diff
@@ -115,6 +115,7 @@ func (e *ExecutablePlugin) Run(timeout time.Duration) (Response, error) {
 	e.cmd.Start()
 	e.captureStderr()
 	go func() {
+	OK:
```
Comment (IRCody) [inline control/plugin/execution.go]: I think this would be clearer as a loop vs a goto.

File: plugin/collector/snap-plugin-collector-mock2/mock/mock.go [hunk 3]
```diff
@@ -56,14 +58,24 @@ func (f *Mock) CollectMetrics(mts []plugin.MetricType) ([]plugin.MetricType, err
...
 				longLine = append(longLine, letterBytes[rand.Intn(len(letterBytes))])
 			}
-			fmt.Println(string(longLine))
+			fmt.Fprintln(os.Stdout, string(longLine))
 		}
+
+		if c, ok := mts[i].Config().Table()["long_stderr_log"]; ok && c.(ctypes.ConfigValueBool).Value {
+			letterBytes := "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
+			longLine := []byte{}
+			for i := 0; i < bufio.MaxScanTokenSize; i++ {
```
Comment (IRCody) [inline plugin/collector/snap-plugin-collector-mock2/mock/mock.go]: Is the goal here to append to longline until it is larger than the MaxScanTokenSize?

File: control/plugin/execution.go (hunk 1 above)
Comment (katarzyna-z) [inline control/plugin/execution.go]: I don't see any special reasons to use `Readline()` instead of `ReadString('\n')`. I changed `Readline()`to `ReadString('\n')` to avoid parsing to string.

File: control/plugin/execution.go (hunk 2 above)
Comment (katarzyna-z) [inline control/plugin/execution.go]: OK, I changed it, now loops are in use.

File: plugin/collector/snap-plugin-collector-mock2/mock/mock.go (hunk 3 above)
Comment (katarzyna-z) [inline plugin/collector/snap-plugin-collector-mock2/mock/mock.go]: Here the goal is to have `longline` with length equal to `MaxScanTokenSize`. The condition in `Scan()` method has following form:
```
if len(s.buf) >= s.maxTokenSize || len(s.buf) > maxInt/2 {
				s.setErr(ErrTooLong)
				return false
}
```

File: control/plugin/execution.go [hunk 4]
```diff
@@ -115,20 +115,35 @@ func (e *ExecutablePlugin) Run(timeout time.Duration) (Response, error) {
...
+				reader := bufio.NewReader(e.stdout)
+				log, err := reader.ReadString('\n')
+
+				execLogger.
+					WithField("plugin", path.Base(e.cmd.Path())).
+					WithField("io", "stdout").
+					WithField("scanner_err", stdOutScanner.Err()).
+					WithField("read_string_err", err).
+					Warn(log)
+				continue
```
Comment (IRCody) [inline control/plugin/execution.go]: I don't think this continue is needed.

Also there is still a case where we will want to break out of the loop right? Otherwise this goroutine will never exit?

Comment (katarzyna-z) [inline control/plugin/execution.go]: I made a small correction in code to finish the loop after scanning. Currently, I don't see solution without `continue`. Please take a look at this. If you have another idea, I'm open for your suggestions.

Comment (IRCody) [inline control/plugin/execution.go]: In the iteration I was commenting on the continue served no purpose as there wasn't code executed after it. The update to add break below it changes that behavior.

File: control/plugin/execution.go [hunk 5]
```diff
@@ -167,12 +183,27 @@ func (e *ExecutablePlugin) Kill() error {
...
+			for stdErrScanner.Scan() {
+				execLogger.
+					WithField("plugin", path.Base(e.cmd.Path())).
+					WithField("io", "stderr").
+					Debug(stdErrScanner.Text())
+			}
 
+			if err := stdErrScanner.Err(); err != nil {
+				reader := bufio.NewReader(e.stderr)
+				log, err := reader.ReadString('\n')
```
Comment (jcooklin) [inline control/plugin/execution.go]: we need to handle the err from `ReadString`

```
log, err2 := reader.ReadString('\n')
				if err2 == io.EOF {
					break
				}
```
Without the above block when the plugin stops the go routine never exits.  You can see this by loading the modified mock2 plugin and starting the following task and then finally stop (ctrl-c) snapd.
```
---
  version: 1
  schedule: 
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow: 
    collect: 
      metrics: 
        /intel/mock/foo: {}
        /intel/mock/bar: {}        
      config: 
        /intel/mock: 
          name: "root"
          password: "secret"          
          long_stderr_log: true
```
img

File: control/plugin/execution.go [hunk 6]
```diff
@@ -167,12 +183,27 @@ func (e *ExecutablePlugin) Kill() error {
...
+
+				execLogger.
+					WithField("plugin", path.Base(e.cmd.Path())).
+					WithField("io", "stderr").
+					WithField("scanner_err", stdErrScanner.Err()).
+					WithField("read_string_err", err).
```
Comment (jcooklin) [inline control/plugin/execution.go]: No need to called stdErrScanner.Err() twice (use err).

File: control/plugin/execution.go [hunk 7]
```diff
@@ -115,21 +115,37 @@ func (e *ExecutablePlugin) Run(timeout time.Duration) (Response, error) {
...
+					execLogger.WithFields(log.Fields{
+						"plugin": path.Base(e.cmd.Path()),
+						"io":     "stdout",
+					}).Debug(stdOutScanner.Text())
+				}
 			}
+
+			if err := stdOutScanner.Err(); err != nil {
+				reader := bufio.NewReader(e.stdout)
+				log, err := reader.ReadString('\n')
```
Comment (jcooklin) [inline control/plugin/execution.go]: Same comments made below on the stderr routine apply here (re: handle ReadString error).

**Comment by katarzyna-z** [comment]
Thanks for review. I made a correction. Could you check it?

**Comment by IRCody** [comment]
LGTM. @jcooklin?
