### PR TITLE
Fixed 1520: Cannot remove an Ended Task

### LINKED ISSUE #1520: Cannot remove an Ended Task (windowed scheduler)
## What happened:
An "_Ended_" task cannot be removed - neither directly removing nor after prior stopping 

This happens for a [**windowed schedule**](https://github.com/intelsdi-x/snap/blob/master/docs/TASKS.md#schedule) for which `stop_timestamp` is defined. That means that after this time the task is ended - this is related to changing the status from "_Running_" to "_Ended_" in line [pkg/schedule/windowed_schedule.go#L101](https://github.com/intelsdi-x/snap/blob/85079bc6f854bc9dfa00921d111e0e5fbec4943b/pkg/schedule/windowed_schedule.go#L101).

## Steps to reproduce it
1) Run an exemplary task manifest with window schedule, for example:
```

  "version": 1,
  "schedule": {
    "type": "windowed",
    "interval": "3s",
    "start_timestamp": "2017-02-15T13:20:56+01:00",
    "stop_timestamp": "2017-02-15T13:48:35+01:00"
  },
  "workflow": {
   [...]
}
```
2) After a time `stop_timestamp` the state of task should be "_Ended_"
```
$ snaptel task list
ID                                       NAME                                            STATE           HIT     MISS    FAIL    CREATED                 LAST FAILURE
5db259f7-3403-421d-896a-78aa15031c80     Task-5db259f7-3403-421d-896a-78aa15031c80       Ended           38      0       0       1:46PM 2-15-2017

```
3) Try to remove the task:
```
$ snaptel task remove 5db259f7-3403-421d-896a-78aa15031c80

Error stopping task:
Task must be stopped
```

4) So, let's stop the task at first and then try to remove it once again:
```
$ snaptel task stop 5db259f7-3403-421d-896a-78aa15031c80
Task stopped:
ID: 5db259f7-3403-421d-896a-78aa15031c80
```
Notice that even stop command looks like be executed successfully, the state of task does NOT change to _Stopped_ (it is still _Ended_)
```
snaptel task list
ID                                       NAME                                            STATE           HIT     MISS    FAIL    CREATED                 LAST FAILURE
5db259f7-3403-421d-896a-78aa15031c80     Task-5db259f7-3403-421d-896a-78aa15031c80       Ended           38      0       0       1:46PM 2-15-2017

```
Still, cannot remove this task even after trying to stop it a prior:
```
$ snaptel task remove 5db259f7-3403-421d-896a-78aa15031c80
Error stopping task:
Task must be stopped
```

It looks like a standstill.

### PR DESCRIPTION
**Pull request by IzabellaRaulin**
Fixed #1520 

**It's READY to review :)**

### To do:
- [x] Adding medium tests
- [x] Making an Ended state resumable
  
### Summary of changes:
1) Added documentation about _Ended_ state in docs/TASKS.md
2) **_Ended_ tasks can be removed**
See [scheduler/task.go#L431](https://github.com/intelsdi-x/snap/compare/master...IzabellaRaulin:fixed_1520?expand=1#diff-77f163e381dd113e90ebd1bd76479b54R431))
 **Before** trying to remove _Ended_ task:
      ```
     $ snaptel task remove 5db259f7-3403-421d-896a-78aa15031c80
     Error stopping task:
     Task must be stopped
      ```
     Notice that stopping an _Ended_ task did not work either (the state still was _Ended_, so it was a standpoint).

      **After**  removing _Ended_ task directly works fine :
      ```
      $ snaptel task remove 71cf766a-7d95-48ed-ad74-f73853545476
     Task removed:
     ID: 71cf766a-7d95-48ed-ad74-f73853545476

     //verification (for this example, a task list should be empty now)
	$ snaptel task list
	No task found. Have you created a task?
      ```
  

3) **An _Ended_ state migh be resumed if the schedule is still valid**
    In `startTask()` there is a check if the schedule is still valid at this point of time, see ([scheduler/scheduler.go#L487](https://github.com/intelsdi-x/snap/compare/master...IzabellaRaulin:fixed_1520?expand=1#diff-9667cfa1ad6b8b445794f7c2469f069fR487)). 
      **Before** trying to restart _Ended_ task:
      ```
      $ snaptel task start       fc303c34-0484-4507-b0f8-7f7c526d3983
      Error starting task:
      error 0: Subscription already exists
      ```
      **After** trying to restart _Ended_ task:
      (an approriate message will be returned if the schedule is not valid, what happens for windowed schedule)
      ```
      $ snaptel task start 71cf766a-7d95-48ed-ad74-f73853545476
      Error starting task:
      error 0: Task is ended. Cannot be restarted.
      ```

    Notice: if another scheduler also puts a task into an ended state, which is being proposed in work related with a single run task, it may make sense for the ended task to be restartable.

4) **Added an appropriate message that tasks in _Ended_ state cannot be stopped**
      **Before:** trying to stop an _Ended_ task
      Stopping an _Ended_ task does not work - there was no message, however, state of task still was _Ended_

      **After:** trying to stop an _Ended_ task
      An appropriate message will be returned
      ```
     $ snaptel task stop 71cf766a-7d95-48ed-ad74-f73853545476
     Error stopping task:
     error 0: Task is ended. Only running tasks can be stopped.
      ```

### Diagram for _Ended_ task
This diagram presents flow for _Ended_ task (sum up all points above):

taskendedstatediagram

## Testing done:
- manually tested
- medium tests

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by andrzej-k** [comment]
@IzabellaRaulin: Do you think that it would make sense to open an Issue for https://github.com/raintank/snap-plugin-collector-snapstats to include "Ended" state in exposed metrics?

File: scheduler/scheduler_test.go [hunk 1]
```diff
@@ -272,36 +272,6 @@ func TestScheduler(t *testing.T) {
...
-			tsk, _ := s.CreateTask(schedule.NewSimpleSchedule(time.Millisecond*100), w, false)
-			So(tsk, ShouldNotBeNil)
-
-			t := s.tasks.Get(tsk.ID())
-			t.state = core.TaskDisabled
-
-			err := s.StartTask(tsk.ID())
-			So(err[0].Error(), ShouldResemble, "Task is disabled. Cannot be started.")
-			So(t.state, ShouldEqual, core.TaskDisabled)
-		})
```
Comment (IzabellaRaulin) [inline scheduler/scheduler_test.go]: FYI, Those tests cases are covered by added tests in scheduler/scheduler_medium_test.go in lines [478](https://github.com/intelsdi-x/snap/pull/1529/files#diff-70085ec92d50bbe2c18f894de2157827R478) and [424](https://github.com/intelsdi-x/snap/pull/1529/files#diff-70085ec92d50bbe2c18f894de2157827R424)

**Comment by kjlyon** [comment]
Documentation and tests are very complete.  👍  LGTM

**Comment by IzabellaRaulin** [comment]
@andrzej-k, I fully agree that all possible task's states should be reflected in metrics provided by snap-plugin-collector-snapstats.

@intelsdi-x/snap-maintainers - is it ok to be merged?

**Comment by andrzej-k** [comment]
LGTM - how about squashing to one commit ? :)

**Comment by jcooklin** [comment]
This PR has an impact on the work being planned related to a single run task as it relates to the "ended" state and whether it can be restarted.  Currently only the windowed scheduler puts a task in the ended state and restarting a task with a windowed schedule doesn't make sense since it would cycle back to ended immediately (for stop time being passed).  If another scheduler also puts a task into an ended state, which is being proposed, it may make sense for the task to be restartable.  In summary, I'm not convinced that an ended state should not be restartable.

**Comment by IzabellaRaulin** [comment]
@jcooklin, I will update this PR to make an Ended state resumable. There is no problem to do that. It will work for the windowed schedule too - trying to restart ended windowed schedule will return an error with message "_Stop time is in the past_" what is the way how it works already for invalid stop_timestamp (see https://github.com/intelsdi-x/snap/blob/988d6ffd189753a6d2b0977ba9ac1dc7b96f4b8c/pkg/schedule/schedule.go#L12). So, I think that sounds good.

**Comment by IzabellaRaulin** [comment]
Squashed to one commit and made an Ended state resumable (if the schedule is still valid). The description of this pull request was updated too.

**Comment by jcooklin** [comment]
LGTM.  :ship: it.
