### PR TITLE
Fixes #1654 - now additional `serror` fields are used and presented

### LINKED ISSUE #1654: Additional `serror` fields are not presented in error message
See package [serror](https://github.com/intelsdi-x/snap/blob/master/core/serror/serror.go#L30)

There is a possibility to set `serror` fields to provide more details about occurring error, however, it is not presented in error message.

This happens when creating task failed and just serror.Error() is taken into account in error message - see [core/task.go#L310](https://github.com/intelsdi-x/snap/blob/master/core/task.go#L310)

For example, for such returned serror:
```
return serror.New(
 ErrPluginIncompatibleWithScheduleType,
 map[string]interface{}{
 "schedule_type": fmt.Sprintf("%T", sch),
 "plugin_name":   plg.Name(),
 "plugin_type":   plg.TypeName(),
 },
)
```
I expected to have "schedule_type", "plugin_name" and "plugin_type" details in snap error message, but they are skipped.

### PR DESCRIPTION
**Pull request by Alrim42**
Fixes #1654 - Additional 'serror' fields are not presented in error message
-
Short information: There is a possibility to set 'serror' fields to provide more details about occurring error, however, it is not presented in error message.

Summary of changes:
- 
- additional information is shown in logs
- updated medium test

How to verify it:
-
1) Create exemplary task manifest, which will result an error, for example:
a) error: `ErrPluginIncompatibleWithScheduleType`
Reason: Schedule type should be `simple` not `streaming`
```
{
  "version": 1,
  "schedule": {
    "type": "streaming",
    "interval": "1s"
  },
  "max-failures": 1,
  "workflow": {
    "collect": {
      "metrics": {
        "/intel/psutil/load/load15": {},
        "/intel/psutil/load/load5": {},
        "/intel/psutil/vm/available": {},
        "/intel/psutil/vm/free": {},
        "/intel/psutil/vm/used": {}
      },
      "publish": [
        {
          "plugin_name": "influxdb",
          "config": {
            "host": "${INFLUXDB_HOST}",
            "port": 8086,
            "database": "test",
            "user": "admin",
            "password": "admin",
            "scheme": "http",
            "skip-verify": false,
            "isMultiFields": true
          }
        }
      ]
    }
  }
}
```
b) error: `ErrMultipleStreamingPlugins`
Reason: Only one streaming collector can be used in task manifest (here task wants to use metrics from two streaming collectors)
```
{
  "version": 1,
  "schedule": {
    "type": "streaming",
    "interval": "5s"
  },
  "max-failures": 1,
  "workflow": {
    "collect": {
      "metrics": {
        "/intel/streaming/random/float": {},
        "/intel/streaming/random/int": {},
        "/intel/streaming2/random2/float": {},
        "/intel/streaming2/random2/int": {}       
      },
      "publish": [
        {
          "plugin_name": "influxdb",
          "config": {
            "host": "${INFLUXDB_HOST}",
            "port": 8086,
            "database": "test3",
            "user": "admin",
            "password": "admin",
            "scheme": "http",
            "skip-verify": false,
            "isMultiFields": true
          }
        }
      ]
    }
  }
}
```

2) Create task (below are examples used in tests)
a) from exemplary task manifest (1a)
```
$ snaptel task create -t test.json --name="Wrong_types"
Using task manifest to create task
Error creating task: Plugin is incompatible with the tasks schedule type.
```

Logs:
```
DEBU[2017-08-17T16:02:01+02:00] API request                                   _module=_mgmt-rest index=6 method=POST url=/v1/tasks
DEBU[2017-08-17T16:02:01+02:00] Setting stop-on-failure limit for task        _block=OptionStopOnFailure _module=core consecutive failure limit=1 task-id=3aa3cc86-edef-48f5-b10f-421465aded4a task-name=Task-3aa3cc86-edef-48f5-b10f-421465aded4a
ERRO[2017-08-17T16:02:01+02:00] error creating task                           _error=Plugin is incompatible with the tasks schedule type. _fields=map[plugin_name:psutil plugin_type:collector schedule_type:*schedule.StreamingSchedule] _file=core/task.go _function=CreateTaskFromContent
DEBU[2017-08-17T16:02:01+02:00] API response                                  _module=_mgmt-rest index=6 method=POST status=Internal Server Error status-code=500 url=/v1/tasks
```

b) from exemplary task manifest (1b)
```
$ snaptel task create -t test2.json --name="2_streaming_collectors"
Using task manifest to create task
Error creating task: Multiple streaming plugins within the same task is not supported.
schedule_type: *schedule.StreamingSchedule
num_of_collectors: 2
```

Logs:
```
DEBU[2017-08-17T16:04:44+02:00] API request                                   _module=_mgmt-rest index=7 method=POST url=/v1/tasks
DEBU[2017-08-17T16:04:44+02:00] Setting stop-on-failure limit for task        _block=OptionStopOnFailure _module=core consecutive failure limit=1 task-id=0cbb08a4-8c6f-4119-94d4-2309baf650b0 task-name=Task-0cbb08a4-8c6f-4119-94d4-2309baf650b0
ERRO[2017-08-17T16:04:44+02:00] error creating task                           _error=Multiple streaming plugins within the same task is not supported. _fields=map[num_of_collectors:2 schedule_type:*schedule.StreamingSchedule] _file=core/task.go _function=CreateTaskFromContent
DEBU[2017-08-17T16:04:44+02:00] API response                                  _module=_mgmt-rest index=7 method=POST status=Internal Server Error status-code=500 url=/v1/tasks
```

Testing done:
- 
- small test passed
- medium test passed
- large test passed
- legacy test passed
- manual test satisfying

@intelsdi-x/snap-maintainers

### CODE REVIEW

File: core/task_medium_test.go [hunk 1]
```diff
@@ -276,15 +274,32 @@ func TestCreateTaskFromContent(t *testing.T) {
...
+		So(serr, ShouldNotBeNil)
+		So(serr.Errors()[0].Error(), ShouldEqual, "invalid character '-' in numeric literal")
 
 		err = deleteTaskFile(YAML_FILE)
 		So(err, ShouldBeNil)
 	})
 
+	Convey("Bad call to CreateTaskFromContent - no routine", t, func() {
+		err := createTaskFile(JSON_FILE, JSON_FILE_CONTENT)
+		So(err, ShouldBeNil)
```
Comment (IzabellaRaulin) [inline core/task_medium_test.go]: @Alrim42, could you change those tests case to delete task file after it has been successfully created (as a deferred execution)? In this test case, please just put in line 289 `defer deleteTaskFile(JSON_FILE)` and remove the code from lines 299-300, similar for others tests.

File: core/task_medium_test.go [hunk 2]
```diff
@@ -134,7 +126,13 @@ func koRoutine(sch schedule.Schedule,
 	te := &taskErrors{
 		errs: make([]serror.SnapError, 0),
 	}
-	te.errs = append(te.errs, serror.New(errors.New("Dummy error")))
+	te.errs = append(te.errs, serror.New(
+		errors.New("Dummy error."),
```
Comment (IzabellaRaulin) [inline core/task_medium_test.go]: Adding the dot in the end is not necessary, but as you prefer.

File: core/task_medium_test.go [hunk 3]
```diff
@@ -310,10 +325,11 @@ func TestCreateTaskFromContent(t *testing.T) {
...
 		So(err, ShouldBeNil)
 		autoStart := true
-		task, err := CreateTaskFromContent(file, &autoStart, koRoutine)
+		task, serr := CreateTaskFromContent(file, &autoStart, koRoutine)
 		So(task, ShouldBeNil)
-		So(err, ShouldNotBeNil)
-		So(err.Error(), ShouldEqual, "Dummy error")
+		So(serr, ShouldNotBeNil)
+		So(serr.Errors()[0].Error(), ShouldEqual, "Dummy error.")
+		So(serr.Errors()[0].Fields(), ShouldNotBeNil)
```
Comment (IzabellaRaulin) [inline core/task_medium_test.go]: Please add checking if the number of fields and their contents are as expected

File: mgmt/rest/v1/rbody/error.go [hunk 4]
```diff
@@ -47,11 +47,11 @@ func FromSnapError(pe serror.SnapError) *Error {
...
 	fields := make(map[string]string)
 	var msg string
-	for i, err := range errs {
+	for _, err := range errs {
 		for k, v := range err.Fields() {
-			fields[fmt.Sprintf("%s_err_%d", k, i)] = fmt.Sprint(v)
+			fields[fmt.Sprintf("%s", k)] = fmt.Sprint(v)
 		}
-		msg = msg + fmt.Sprintf("error %d: %s ", i, err.Error())
+		msg = msg + fmt.Sprintf("%s", err.Error())
```
Comment (IzabellaRaulin) [inline mgmt/rest/v1/rbody/error.go]: @Alrim42, could you explain to me what is benefit from this change?

File: mgmt/rest/v1/task.go [hunk 5]
```diff
@@ -45,11 +46,23 @@ var (
...
+		for _, e := range errs.Errors() {
+			testSerrors = append(testSerrors, serror.New(errors.New(e.Error()), e.Fields()))
+		}
+
+		log.WithFields(log.Fields{
+			"_file":     "rest/v1/task.go,",
+			"_function": "addTask",
+			"error":     errors.New(testSerrors[0].Error()),
+		}).Error("error adding task")
+		rbody.Write(500, rbody.FromSnapErrors(testSerrors), w)
```
Comment (IzabellaRaulin) [inline mgmt/rest/v1/task.go]: @Alrim42, could you verify if all that added code (lines 51-61) is needed? I think it should be just one line `rbody.Write(500, rbody.FromSnapErrors(errs.Errors()), w)`, but please check it.

File: mgmt/rest/v2/task.go [hunk 6]
```diff
@@ -135,11 +136,18 @@ func (s *Task) CreationTime() time.Time {
...
-		Write(500, FromError(err), w)
+	task, errs := core.CreateTaskFromContent(r.Body, nil, s.taskManager.CreateTask)
+	if errs != nil && len(errs.Errors()) != 0 {
+		testSerrors := make([]serror.SnapError, 0)
+
+		for _, e := range errs.Errors() {
+			testSerrors = append(testSerrors, serror.New(errors.New(e.Error()), e.Fields()))
+		}
+
+		Write(500, FromSnapErrors(testSerrors), w)
```
Comment (IzabellaRaulin) [inline mgmt/rest/v2/task.go]: similar as below

File: core/task_medium_test.go (hunk 2 above)
Comment (Alrim42) [inline core/task_medium_test.go]: I added the dot because all error messages have dots in the end, for example:
```
// ErrPluginIncompatibleWithScheduleType - The error message for when a streaming schedule type references a non streaming plugin or vice versa.
ErrPluginIncompatibleWithScheduleType = errors.New("Plugin is incompatible with the tasks schedule type.")
// ErrMultipleStreamingPlugins - The error message when a task with a streaming schedule refers to multiple streaming plugins.
ErrMultipleStreamingPlugins = errors.New("Multiple streaming plugins within the same task is not supported.")
```

File: cmd/snaptel/task.go [hunk 7]
```diff
@@ -385,10 +385,15 @@ func createTaskUsingTaskManifest(ctx *cli.Context) error {
...
 	if r.Err != nil {
-		errors := strings.Split(r.Err.Error(), " -- ")
-		errString := "Error creating task:"
-		for _, err := range errors {
-			errString += fmt.Sprintf("%v\n", err)
+		errString := "Error creating task: " + fmt.Sprintf("%v\n", r.Err.Error())
+
+		if r.Fields["body"] != nil {
+			fieldsInsideFieldsBody, _ := r.Fields["body"].(map[string]interface{})
+			fieldsInsidefields, _ := fieldsInsideFieldsBody["fields"].(map[string]interface{})
```
Comment (Alrim42) [inline cmd/snaptel/task.go]: This structure represents content of fields. For example with error `ErrPluginIncompatibleWithScheduleType` this structure could be like this one:
`map[plugin_name:psutil plugin_type:collector schedule_type:*schedule.StreamingSchedule]`

File: cmd/snaptel/task.go [hunk 8]
```diff
@@ -448,7 +453,7 @@ func createTaskUsingWFManifest(ctx *cli.Context) error {
 	r := pClient.CreateTask(t.Schedule, wf, t.Name, t.Deadline, !ctx.IsSet("no-start"), t.MaxFailures)
 	if r.Err != nil {
 		errors := strings.Split(r.Err.Error(), " -- ")
-		errString := "Error creating task:"
+		errString := "Error creating task: "
 		for _, err := range errors {
```
Comment (Alrim42) [inline cmd/snaptel/task.go]: It should be done in the same way, you are right. I will change it.

File: mgmt/rest/v1/rbody/error.go (hunk 4 above)
Comment (Alrim42) [inline mgmt/rest/v1/rbody/error.go]: Previously error message was without this additional string, so that is why I removed it. But I see that it could stay, so I will revert this.

File: core/task.go [hunk 9]
```diff
@@ -295,21 +295,29 @@ func CreateTaskFromContent(body io.ReadCloser,
...
-		return nil, errors.New("Missing workflow creation routine")
+		return nil, serror.New(errors.New("Missing workflow creation routine"))
 	}
 	task, errs := fp(sch, tr.Workflow, *mode, opts...)
 	if errs != nil && len(errs.Errors()) != 0 {
 		var errMsg string
+		var errorFields map[string]interface{}
 		for _, e := range errs.Errors() {
-			errMsg = errMsg + e.Error() + " -- "
+			errorFields = e.Fields()
```
Comment (IzabellaRaulin) [inline core/task.go]: `errorFields` will be overwritten on each of iteration, so only Fields from the last errors will be visible. It should be managed in a different manner.

File: mgmt/rest/v1/task.go [hunk 10]
```diff
@@ -45,11 +45,12 @@ var (
 )
 
 func (s *apiV1) addTask(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
-	task, err := core.CreateTaskFromContent(r.Body, nil, s.taskManager.CreateTask)
-	if err != nil {
-		rbody.Write(500, rbody.FromError(err), w)
+	task, errs := core.CreateTaskFromContent(r.Body, nil, s.taskManager.CreateTask)
```
Comment (IzabellaRaulin) [inline mgmt/rest/v1/task.go]: `core.CreateTaskFromContent` returns `serr`, not slice of errors. Name of variable `errs` is misleading! What is more, checking `len(errs.Error()) != 0 ` does not have sense (see the [line 49](https://github.com/intelsdi-x/snap/pull/1701/files#diff-f7e0c90ee57f3f6bd2ab3a6199986599R49)

File: mgmt/rest/v2/task.go [hunk 11]
```diff
@@ -135,11 +135,12 @@ func (s *Task) CreationTime() time.Time {
 }
 
 func (s *apiV2) addTask(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
-	task, err := core.CreateTaskFromContent(r.Body, nil, s.taskManager.CreateTask)
-	if err != nil {
-		Write(500, FromError(err), w)
+	task, errs := core.CreateTaskFromContent(r.Body, nil, s.taskManager.CreateTask)
```
Comment (IzabellaRaulin) [inline mgmt/rest/v2/task.go]: The same as above

**Comment by IzabellaRaulin** [comment]
Hello @Alrim42, so far it looks goods. The description of this PR seems to be outdated. Could you update it? The another thing is there plan to present the content of  `fields` in REST API response? Currently, empty fields are returned as below:

```
  "body": {
    "message": "Plugin is incompatible with the tasks schedule type.",
    "fields": {}
  }
```
